import math
f=open('script2',"w")
for i in range(400):
    f.write("line")
    f.write("\n")
    x1=int(25*math.cos(5*i)+25*math.cos(4*i))
    y1=int(25*math.sin(5*i)+25*math.sin(i))
    z1=int(50*math.sin(2*i))
    x2=int(25*math.cos(5*(i+1))+25*math.cos(4*(i+1)))
    y2=int(25*math.sin(5*(i+1))+25*math.sin((i+1)))
    z2=int(50*math.sin(2*(i+1)))
    f.write(str(x1+50)+" "+str(y1+50)+" "+str(z1+50)+" "
            +str(x2+50)+" "+str(y2+50)+" "+str(z2+50))
    f.write("\n")
f.write("ident\n")
f.write("scale\n")
f.write("2 2 2\n")
f.write("apply\n")
f.write("display\n")
f.write("ident\n")
f.write("scale\n")
f.write("2 2 2\n")
f.write("apply\n")
f.write("display\n")
f.write("ident\n")
f.write("move\n")
f.write("0 50 0\n")
f.write("apply\n")
f.write("display\n")
f.write("save\n")
f.write("pic2.png\n")
f.close()
